name: Cypress Tests

on: [ push ]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node18.6.0-chrome105-ff104
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        uses: cypress-io/github-action@v4.2.0
        with:
          runTests: false
          build: npm install

      - name: Cypress info
        run: npx cypress info

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          install: false
          browser: chrome
          start: npx cypress open --browser chrome
